version: '3.7'
services: 
  web:
    build:
      context: .
      dockerfile: docker/Dockerfiles/Dockerfile.django
    command: python /app/manage.py runserver 0.0.0.0:8080
    volumes:
      - ./app:/app
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - pgAdmin4
    networks:
      network-database:
        ipv4_address: 172.23.0.2

  postgres:
    build:
      context: .
      dockerfile: docker/Dockerfiles/Dockerfile.postgres
    image: postgres
    container_name: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passwordRoot
    networks:
      network-database:
        ipv4_address: 172.23.0.3

  pgAdmin4:
    container_name: pgAdmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.postgres.org
      PGADMIN_DEFAULT_PASSWORD: passwordRoot
    depends_on: 
      - postgres
    ports:
      - 8081:80
    networks:
      network-database:
        ipv4_address: 172.23.0.4

networks:
  network-database:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/23